version: '3'

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r 127.0.0.1:21117
    volumes:
      - ./data:/root
    network_mode: "host"
    # Ports section is abandoned when using "host" network mode
    #ports:
    #  - 21115:21115
    #  - 21116:21116
    #  - 21116:21116/udp
    #  - 21118:21118
    depends_on:
      - hbbr
    restart: unless-stopped


  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    # Ports section is abandoned when using "host" network mode
    #ports:
    #  - 21117:21117
    #  - 21119:21119
    restart: unless-stopped

