services:
  pytorch:
    image: rocm/pytorch:latest
    group_add:
      - video
    devices:
      - /dev/kfd
      - /dev/dri
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ipc: host
    ports:
      - "8888:8888"
    restart: unless-stopped
    stdin_open: true
    tty: true
