name: Test Runner on Multiple Platforms

on:
  push:
    branches: [main, master]
    paths:
      - "runner/**"
      - "scripts/**" 
      - ".github/workflows/test.yml" 
  pull_request:
    branches: [main, master]
    paths:
      - "runner/**"
      - "scripts/**" 
  workflow_dispatch: 

env:
  CARGO_TERM_COLOR: always
  PROJECT_DIR: runner

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            runner/target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ matrix.os }}-cargo-

      - name: Build
        working-directory: ${{ github.workspace }}/${{ env.PROJECT_DIR }}
        run: cargo build

      - name: Run tests
        working-directory: ${{ github.workspace }}/${{ env.PROJECT_DIR }}
        run: cargo test

      - name: Lint
        working-directory: ${{ github.workspace }}/${{ env.PROJECT_DIR }}
        run: cargo clippy -- -D warnings

      # Basic functionality test - just check that it can run
      - name: Test List Scripts (Unix)
        if: runner.os != 'Windows'
        working-directory: ${{ github.workspace }}
        run: |
          cd ${{ env.PROJECT_DIR }}
          cargo run -- -s ../scripts list

      - name: Test List Scripts (Windows)
        if: runner.os == 'Windows'
        working-directory: ${{ github.workspace }}
        run: |
          cd ${{ env.PROJECT_DIR }}
          cargo run -- -s ..\scripts list
